#!/bin/bash
#SBATCH --time=71:59:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=16gb
#SBATCH --job-name=reactants_full_scan
#SBATCH --partition=regular


module load    Gaussian/16.B.01
srun g16  reactants_scan.com reactants_scan.out
